<?php

// $Id$

/**
 * @file
 *
 * Installs the required associations/forms.
 */

define('ISLANDORA_CHEM_SP_MODS_FORM_NAME', 'Islandora Chem MODS Form');

/**
 * Implementation of hook_install.
 */
function islandora_chem_sp_install() {
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (!XMLFormDatabase::Exists(ISLANDORA_CHEM_SP_MODS_FORM_NAME)) {
    $module_path = drupal_get_path('module', 'islandora_chem_sp');
    $definition = new DOMDocument();
    $definition->load($module_path . '/xml/mods_chem.xml');
    XMLFormDatabase::Create(ISLANDORA_CHEM_SP_MODS_FORM_NAME, $definition);
  }
  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'islandora:sp_chem', 'Islandora Chem MODS Form'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'islandora:sp_chem';
    $object->form_name = 'Islandora Chem MODS Form';
    $object->dsid = 'MODS';
    $object->title_field = "['titleInfo']['title']";
    $object->transform = 'mods_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }
}

/**
 * Implementation of hook_uninstall.
 */
function islandora_chem_sp_uninstall() {
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (XMLFormDatabase::Exists(ISLANDORA_CHEM_SP_MODS_FORM_NAME)) {
    XMLFormDatabase::Delete(ISLANDORA_CHEM_SP_MODS_FORM_NAME);
  }
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where content_model = "%s" and form_name = "%s"', 'islandora:sp_chem', 'Islandora Chem MODS Form'));
  if ($result) {
    db_query('DELETE FROM {islandora_content_model_forms} WHERE content_model = "%s" and form_name = "%s"', 'islandora:sp_chem', 'Islandora Chem MODS Form');
  }
}