<?php

/**
 * @file
 *
 * Installs the required associations/forms.
 */
define('ISLANDORA_CHEM_SP_MODS_FORM_NAME', 'Islandora Chem MODS Form');

/**
 * Implementation of hook_install.
 */
function islandora_chem_sp_install() {
  module_load_include('inc', 'islandora_chem_sp', 'islandora_chem_sp_schema');
  drupal_install_schema('islandora_chem_sp');
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (!XMLFormDatabase::Exists(ISLANDORA_CHEM_SP_MODS_FORM_NAME)) {
    $module_path = drupal_get_path('module', 'islandora_chem_sp');
    $definition = new DOMDocument();
    $definition->load($module_path . '/xml/mods_chem.xml');
    XMLFormDatabase::Create(ISLANDORA_CHEM_SP_MODS_FORM_NAME, $definition);
  }
  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'quantumchem:sp_chem', 'Islandora Chem MODS Form'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'quantumchem:sp_chem';
    $object->form_name = 'Islandora Chem MODS Form';
    $object->dsid = 'MODS';
    $object->title_field = "['titleInfo']['title']";
    $object->transform = 'mods_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }
}

function islandora_chem_sp_requirements($phase) {
  global $base_url;

  $requirements = array();

  $requirements['fedora-cdw']['title'] = t("ChemDoodleWeb installed");
  $module_path = drupal_get_path('module', 'islandora_chem_sp');
  $result = file_exists($module_path . '/js/ChemDoodleWeb/install/ChemDoodleWeb.js');
  if (!$result) {
    $requirements['fedora-cdw']['value'] = t('ChemDoodleWeb is not installed');
    $requirements['fedora-cdw']['description'] = t('Islandora will not be able to show 3D structures. Click <a href="http://web.chemdoodle.com/">here</a> for installation instructions');
    $requirements['fedora-cdw']['severity'] = REQUIREMENT_WARNING;
  }
  else {
    $requirements['fedora-cdw']['value'] = t("Installed");
    $requirements['fedora-cdw']['severity'] = REQUIREMENT_OK;
  }

  $requirements['fedora-obabel']['title'] = t("Open Babel installed");
  $result = exec('obabel');
  if (!$result) {
    $requirements['fedora-obabel']['value'] = t('Open Babel is not in the path');
    $requirements['fedora-obabel']['description'] = t('Islandora will not be able to convert chemistry files. Click <a href="http://openbabel.org">here</a> for installation instructions');
    $requirements['fedora-obabel']['severity'] = REQUIREMENT_WARNING;
  }
  else {
    $requirements['fedora-obabel']['value'] = t("Installed");
    $requirements['fedora-obabel']['severity'] = REQUIREMENT_OK;
  }

  return $requirements;
}

/**
 * Implementation of hook_uninstall.
 */
function islandora_chem_sp_uninstall() {
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (XMLFormDatabase::Exists(ISLANDORA_CHEM_SP_MODS_FORM_NAME)) {
    XMLFormDatabase::Delete(ISLANDORA_CHEM_SP_MODS_FORM_NAME);
  }
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where content_model = "%s" and form_name = "%s"', 'quantumchem:sp_chem', 'Islandora Chem MODS Form'));
  if ($result) {
    db_query('DELETE FROM {islandora_content_model_forms} WHERE content_model = "%s" and form_name = "%s"', 'quantumchem:sp_chem', 'Islandora Chem MODS Form');
  }
}